name: Flutter Auto Build (APK & AAB)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      制造- name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # یہاں اب بالکل وہی نام ہیں جو آپ نے گٹ ہب پر بنائے ہیں
      - name: Create key.properties from GitHub Secrets
        run: |
          echo "storePassword=${{ secrets.STOREPASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEYPASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEYALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload APK & AAB Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-Builds
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
